# Generated by Django 3.2.5 on 2021-09-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racks', '0002_python_rack'),
    ]

    operations = [
        migrations.CreateModel(
            name='pandas_rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('explanation', models.CharField(max_length=10000)),
                ('tips_and_tricks', models.CharField(max_length=250)),
                ('code', models.TextField(null=True)),
            ],
        ),
    ]
